services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - openimpro_data:/app/database
      - openimpro_shows:/app/shows

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    restart: always
    ports:
      - "80:80"

volumes:
  openimpro_data:
  openimpro_shows: