services:
  backend:
    build:
      context: ./backend
    environment:
      - NODE_ENV=production
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECRET_TOKEN=${SECRET_TOKEN}
      - CORS_ORIGIN=${CORS_ORIGIN}
    volumes:
      - ./backend/shows:/app/shows
      - ./backend/db.json:/app/db.json

  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}
    depends_on:
      - backend