FROM node:20-alpine
WORKDIR /app

# Install nodemon globally for stability in the container
RUN yarn global add nodemon

COPY package.json yarn.lock* ./
RUN yarn install

COPY . .

EXPOSE 3000

CMD ["yarn", "dev"]